import { ThemeProvider } from "@mui/material";
import type { AppProps } from "next/app";
import NavbarKino from "../components/NavbarKino";
import { theme } from "../../styles/theme";
import "../../styles/globals.css";
import FooterKino from "../components/FooterKino";
import Head from "next/head";
import React from "react";
import LoggedInProvider from "../components/login/IsLoggedIn";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Risbäck Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <LoggedInProvider>
          <div>
            <NavbarKino />
          </div>
          <div>
            <Component {...pageProps} />
          </div>
          <div>
            <FooterKino />
          </div>
        </LoggedInProvider>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
