import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import { Box } from "@mui/material";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Risbäck Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <h1>Hello fellow developers!</h1>
        <Box sx={{ height: "900px" }}>hello</Box>
      </div>
    </>
  );
};

export default Home;
