import React from 'react';
import { Box } from '@mui/material';

import Head from 'next/head';
import '../../styles/movies.module.css';
import { CustomBtn } from '../components/CustomMUI/CustomUI';
export default function myPages() {
  return (
    <div className="main">
      <Head>
        <title>Risbäck Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomBtn
        btnText={'Log out'}
        btnColor={'error'}
        btnPadding={'5px'}
      ></CustomBtn>
      <Box sx={{ height: '900px' }}>
        <div className="container">
          <h2>Profil</h2>
          <p>Förnamn</p>
          <p>Efternamn</p>
          <p>ID</p>
          <h2>Mina biljetter</h2>
        </div>
      </Box>
    </div>
  );
}
